import { PiGlobeHemisphereWestDuotone } from "react-icons/pi";
import { FaCcDiscover } from "react-icons/fa";
import { RiTwitterXFill } from "react-icons/ri";
import {
  SiVisa,
  SiMastercard,
  SiAmericanexpress,
  SiPaypal,
  SiNetflix,
  SiSpotify,
  SiAmazon,
  SiApple,
  SiGoogle,
  SiMeta,
  SiInstagram,
  SiYoutube,
  SiEbay,
  SiBankofamerica,
  SiChase,
  SiWellsfargo,
  SiGithub,
  SiZoom,
  SiGmail,
  SiTiktok,
  SiLinkedin,
  SiParamountplus,
  SiWhatsapp,
  SiPrime,
} from "react-icons/si";

// Service Icons Mapping
export const serviceIcons = {
  amazon: SiAmazon,
  americanexpress: SiAmericanexpress,
  apple: SiApple,
  bankofamerica: SiBankofamerica,
  chase: SiChase,
  discover: FaCcDiscover,
  ebay: SiEbay,
  gmail: SiGmail,
  github: SiGithub,
  google: SiGoogle,
  instagram: SiInstagram,
  linkedin: SiLinkedin,
  mastercard: SiMastercard,
  meta: SiMeta,
  netflix: SiNetflix,
  paramountplus: SiParamountplus,
  paypal: SiPaypal,
  primevideo: SiPrime,
  spotify: SiSpotify,
  tiktok: SiTiktok,
  visa: SiVisa,
  wellsfargo: SiWellsfargo,
  whatsapp: SiWhatsapp,
  x: RiTwitterXFill,
  youtube: SiYoutube,
  zoom: SiZoom,
  default: PiGlobeHemisphereWestDuotone,
};

// Service Names Mapping
export const serviceNames = {
  amazon: "Amazon",
  americanexpress: "American Express",
  apple: "Apple",
  bankofamerica: "Bank of America",
  chase: "Chase",
  discover: "Discover",
  ebay: "eBay",
  gmail: "Gmail",
  github: "GitHub",
  google: "Google",
  instagram: "Instagram",
  linkedin: "LinkedIn",
  mastercard: "Mastercard",
  meta: "Meta",
  netflix: "Netflix",
  paramountplus: "Paramount Plus",
  paypal: "PayPal",
  primevideo: "Prime Video",
  spotify: "Spotify",
  tiktok: "TikTok",
  visa: "Visa",
  wellsfargo: "Wells Fargo",
  whatsapp: "WhatsApp",
  x: "X",
  youtube: "YouTube",
  zoom: "Zoom",
  default: "Other",
};
