import {
  SiVisa,
  SiMastercard,
  SiAmericanexpress,
  SiDiscover,
  SiPaypal,
  SiNetflix,
  SiSpotify,
  SiAmazon,
  SiApple,
  SiGoogle,
  SiMeta,
  SiInstagram,
  SiYoutube,
  SiHu,
  SiEbay,
  SiBankofamerica,
  SiChase,
  SiWellsfargo,
  SiCiti,
  SiGithub,
  SiZoom,
  SiGmail,
  SiTiktok,
  SiLinkedin,
  SiAmazonprime,
  SiParamountplus,
  SiWhatsapp,
  SiX,
  SiMicrosoft,
} from "react-icons/si";

const serviceIcons = {
  visa: <SiVisa size={32} />,
  mastercard: <SiMastercard size={32} />,
  americanexpress: <SiAmericanexpress size={32} />,
  discover: <SiDiscover size={32} />,
  paypal: <SiPaypal size={32} />,
  netflix: <SiNetflix size={32} />,
  spotify: <SiSpotify size={32} />,
  amazon: <SiAmazon size={32} />,
  apple: <SiApple size={32} />,
  google: <SiGoogle size={32} />,
  meta: <SiMeta size={32} />,
  instagram: <SiInstagram size={32} />,
  youtube: <SiYoutube size={32} />,
  ebay: <SiEbay size={32} />,
  hu: <SiHu size={32} />,
  bankofamerica: <SiBankofamerica size={32} />,
  chase: <SiChase size={32} />,
  wellsFargo: <SiWellsfargo size={32} />,
  citi: <SiCiti size={32} />,
  github: <SiGithub size={32} />,
  zoom: <SiZoom size={32} />,
  gmail: <SiGmail size={32} />,
  tiktok: <SiTiktok size={32} />,
  linkedin: <SiLinkedin size={32} />,
  amazonprime: <SiAmazonprime size={32} />,
  paramountplus: <SiParamountplus size={32} />,
  whatsapp: <SiWhatsapp size={32} />,
  x: <SiX size={32} />,
  microsoft: <SiMicrosoft size={32} />,
};

export default serviceIcons;
