import { PiGlobeHemisphereWestDuotone } from "react-icons/pi";
import {
  SiVisa,
  SiMastercard,
  SiAmericanexpress,
  SiDiscover,
  SiPaypal,
  SiNetflix,
  SiSpotify,
  SiAmazon,
  SiApple,
  SiGoogle,
  SiMeta,
  SiInstagram,
  SiYoutube,
  SiEbay,
  SiBankofamerica,
  SiChase,
  SiWellsfargo,
  SiGithub,
  SiZoom,
  SiGmail,
  SiTiktok,
  SiLinkedin,
  SiAmazonprime,
  SiParamountplus,
  SiWhatsapp,
  SiX,
  SiMicrosoft,
} from "react-icons/si";

// Service Icons Mapping
export const serviceIcons = {
  visa: SiVisa,
  mastercard: SiMastercard,
  americanexpress: SiAmericanexpress,
  discover: SiDiscover,
  paypal: SiPaypal,
  netflix: SiNetflix,
  spotify: SiSpotify,
  amazon: SiAmazon,
  apple: SiApple,
  google: SiGoogle,
  meta: SiMeta,
  instagram: SiInstagram,
  youtube: SiYoutube,
  ebay: SiEbay,
  bankofamerica: SiBankofamerica,
  chase: SiChase,
  wellsfargo: SiWellsfargo,
  github: SiGithub,
  zoom: SiZoom,
  gmail: SiGmail,
  tiktok: SiTiktok,
  linkedin: SiLinkedin,
  amazonprime: SiAmazonprime,
  paramountplus: SiParamountplus,
  whatsapp: SiWhatsapp,
  x: SiX,
  microsoft: SiMicrosoft,
  default: PiGlobeHemisphereWestDuotone,
};

// Service Names Mapping
export const serviceNames = {
  visa: "Visa",
  mastercard: "Mastercard",
  americanexpress: "American Express",
  discover: "Discover",
  paypal: "PayPal",
  netflix: "Netflix",
  spotify: "Spotify",
  amazon: "Amazon",
  apple: "Apple",
  google: "Google",
  meta: "Meta",
  instagram: "Instagram",
  youtube: "YouTube",
  ebay: "eBay",
  bankofamerica: "Bank of America",
  chase: "Chase",
  wellsfargo: "Wells Fargo",
  github: "GitHub",
  zoom: "Zoom",
  gmail: "Gmail",
  tiktok: "TikTok",
  linkedin: "LinkedIn",
  amazonprime: "Amazon Prime",
  paramountplus: "Paramount+",
  whatsapp: "WhatsApp",
  x: "Twitter",
  microsoft: "Microsoft",
  default: "Other",
};
